language: erlang
otp_release:
  - R16B03
before_install:
  - git clone https://github.com/elixir-lang/elixir
  - cd elixir && git checkout tags/v0.12.0 && make && cd ..
before_script: "export PATH=`pwd`/elixir/bin:$PATH"
script: "MIX_ENV=test mix do deps.get, test"